100-hours-a-week/3-team-CareerBee-fe

- components.json
- package.json
- src/components/ui/button.tsx
- src/lib/utils.ts
- tailwind.config.js
- 버튼 컴포넌트 추가
- shadcn-ui에서 가져오기
- 속성 추가
- 페이지에서 확인
- #1
> (Feat) make Button

- package.json
- src/components/ui/filter.tsx
- src/components/ui/input.tsx
- src/components/ui/select.tsx
- src/components/ui/tabs.tsx
- src/components/ui/toggle.tsx
- src/index.css
- tailwind.config.js
- input, tabs, toggelbutton, filtergroup, select 생성 
- shadcn 컴포넌트를 다운 받은 후 props와 variant 조절
- 페이지에서 목업 띄워두고 인터렉션
- #6
> [Common] make form components

- src/index.css
- src/layout/MainLayout.tsx
- tailwind.config.js
- 웹 앱 기반 반응형 사이즈 설정
- max-width: 600px
- 없음
- #10
> [Layout] adjust responsive view size

- src/layout/MainLayout.tsx
- src/pages/Home.tsx
- 백엔드와 api 연동
- axios 사용
- api 호출 정상 리스폰스 확인
-
> [Test] healthcheck with backend

- src/pages/Home.tsx
- response 타입 체킹 추가
- response message가 string인지 체크
- 없음
- 없음
> [API] response type error fix

- src/components/domain/SearchBar.tsx
- src/components/domain/SuggestionList.tsx
- src/components/layout/navbar.tsx
- src/layout/MainLayout.tsx
- src/pages/Home.tsx
- src/pages/Map.tsx
- src/router/index.tsx
- 검색창과 추천 드롭다운 구현
- 기존 Home.tsx를 Map.tsx로 리네이밍하여 도메인 명확성 확보
- 로그인 여부 및 라우트에 따라 다른 Header / Navbar 조건 렌더링 적용
- 
- 
- **지도** 도메인의 의미 전달을 확실히 하기 위해 페이지명과 브랜치 명 **map**으로 변경
> [Map] Implement search bar and suggestion dropdown on map page

- src/components/domain/CompanyCard.tsx
- src/components/domain/MapOverlay.tsx
- src/components/ui/toggle.tsx
- src/hooks/useCompanyDetail.ts
- src/hooks/useFetchSuggestions.ts
- src/layout/MainLayout.tsx
- src/pages/Main.tsx
- src/store/company.ts
- src/store/search.ts
- 검색 추천 API 붙이기
- 헤더가 로그인 상태에 따라 바뀌게 렌더링
- 기업 간단 카드의 토글 버튼 기능 활성화
- 지도 중심에 따라 기업 불러오기
- main.tsx 리팩토링
- useSearchStore, useFetchSuggestions 커스텀 훅을 통해 검색어 상태와 자동완성 요청 로직 분리
- useCompanyDetail 훅을 생성하여 기업 카드 클릭 시 요약 정보 및 북마크 여부 요청 분리
- MapOverlay.tsx로 오버레이 및 카드 관련 로직 분리, 토글 이벤트도 이 안에서 처리
- 
-
> [Map] Refactor&Add minor missing features for map interactions with search and bookmark logic

- src/components/domain/MapOverlay.tsx
- src/hooks/useCompanyDetail.ts
- src/hooks/useFetchSuggestions.ts
- src/pages/CompanyDetail.tsx
- src/pages/Login.tsx
- src/pages/Main.tsx
- src/pages/OAuthCallback.tsx
- API 주소 환경변수로 등록 
- .env에 VITE_API_URL 설정
- 
-
> [API] apply environment variable for API base URL

- src/components/domain/CompanyTitle.tsx
- src/components/domain/company/benefit.tsx
- src/components/domain/company/defaultTab.tsx
- src/components/domain/company/issue.tsx
- src/components/domain/company/recruit.tsx
- src/components/ui/tabs.tsx
- src/layout/MainLayout.tsx
- src/pages/CompanyDetail.tsx
- 탭 컴포넌트(기본, 채용공고, 최근이슈, 복지) 제작
- 갤러리 내부 이미지 사이즈 조절
- 금액 단위 뷰 설정
- 
- 
-
> [Company] make tab components & design tiny details

- src/components/domain/MapOverlay.tsx
- src/components/ui/filter.tsx
- src/hooks/useCompanyDetail.ts
- src/layout/MainLayout.tsx
- src/pages/Main.tsx
- src/store/marker.ts
- 필터 기능 구현
- 스크롤 달기
- 맵 크기 조정
- marker 이미지 가졍괴
- 
- 
-
> [Map] make filter

- src/components/domain/MapOverlay.tsx
- src/components/ui/filter.tsx
- src/hooks/useCompanyDetail.ts
- src/hooks/useFetchSuggestions.ts
- src/lib/axios.ts
- src/pages/CompanyDetail.tsx
- src/pages/Login.tsx
- src/pages/Main.tsx
- src/pages/OAuthCallback.tsx
- src/store/auth.ts
- 로그아웃 로직 추가
- 커스텀 axios 사용
- 
- 
- 로그아웃 버튼은 안 만듬
> [Member] add logout logic&use custom axios 

- src/components/ui/filter.tsx
- src/lib/axios.ts
- src/pages/Login.tsx
- src/pages/OAuthCallback.tsx
- src/store/auth.ts
- 저장 필터 적용 안되는 문제 해결
- console.log() 정리
- 
- 
-
> [Map] fix save filter error

- src/components/domain/CompanyCard.tsx
- src/components/domain/CompanyTitle.tsx
- src/components/domain/SuggestionList.tsx
- src/components/domain/company/benefit.tsx
- src/components/domain/company/defaultTab.tsx
- src/components/layout/navbar.tsx
- src/layout/MainLayout.tsx
- src/pages/CompanyDetail.tsx
- 네비게이션 바에 배경 추가
- 메인 컴포넌트에 스크롤 추가
- benefit 컴포넌트 타입 오류 해결
- 
- 
-
> [Company] fix design errors

- src/App.tsx
- src/assets/loader.css
- src/components/ui/button.tsx
- src/components/ui/loader.tsx
- src/components/ui/toaster.tsx
- src/hooks/useGlobalErrorToast.ts
- src/hooks/useToast.ts
- src/lib/axios.ts
- src/lib/errorEvents.ts
- src/pages/Main.tsx
- src/pages/Mypage.tsx
- src/pages/OAuthCallback.tsx
- src/router/index.tsx
- 로그아웃 기능 개발
- 마이페이지에 로그아웃 버튼 퍼블리싱
- 로그인 토큰 필요 API 요청 실패시 401 분기
- 로그인 중 로딩 페이지 제작
- 
- 
- #54  #52 https://github.com/100-hours-a-week/3-team-ssammu-wiki/issues/73
> [Member] implement logout funtion on MyPage

- public/mock/CompanyDetail.json
- src/components/domain/company/benefit.tsx
- src/components/domain/company/defaultTab.tsx
- src/components/domain/company/issue.tsx
- src/components/domain/company/recruit.tsx
- src/components/domain/company/techstack.tsx
- src/pages/CompanyDetail.tsx
- 기술 스택 탭 제작
- 모든 탭에 가로 패딩 추가
- 채용 정보 디자인 오류 변경.
- 
- mock data로 작업
-
> [Company] made techstack tab & tiny design changes on company page

- package.json
- public/mock/CompanyDetail.json
- src/components/domain/company/defaultTab.tsx
- tailwind.config.js
- 주소 2줄까지 표시 그 외는 ... 표시
- 사원 수 0명이면 - 표시
- 홈페이지 url 2줄까지 표시 그 외는 ... 표시
- 매출액, 영업 이익 조, 억, 만으로 표시
- mock data 변경
- 
- mock data 로 작업
-
> [Company] improve formatting on defaultTab

- src/components/domain/CompanyTitle.tsx
- src/components/domain/MapOverlay.tsx
- src/components/ui/toast.tsx
- src/components/ui/toaster.tsx
- src/hooks/useFetchBookmarkStatus.ts
- src/hooks/useFetchCompanyCard.ts
- src/index.css
- src/lib/toggleBookmark.ts
- src/pages/CompanyDetail.tsx
- 저장 버튼 기능 구현
- 공유 버튼 기능 구현
- 토스트 메세지 스타일 변경
- 
- 
- #42 #41
> [Company] made save&share button functions

- src/pages/CompanyDetail.tsx
- tailwind.config.js
- vite.config.ts
- 채용 예상 시점 알림 바 제작
- vite 빌드 및 tailwind 최적화
- 
- mock 데이터로 작업
- #53
> [Company] made recruiting rolling bar

- src/components/domain/CompanyCard.tsx
- src/components/domain/CompanyTitle.tsx
- src/components/domain/company/techstack.tsx
- src/components/ui/modal.tsx
- src/components/ui/select.tsx
- src/components/ui/toast.tsx
- src/index.css
- src/pages/Main.tsx
- 내 위치 찾기 버튼 제작
- "muted" 색상 #CBC9C6 으로 변경
- 토스트메세지 디자인 변경
- 
- 크롬에서 테스트
- #39
> [Map] made "move to my location" button

- src/components/ui/filter.tsx
- src/hooks/useFetchBookmarkStatus.ts
- src/pages/CompanyDetail.tsx
- src/pages/Main.tsx
- 기업 상세 페이지 불러오는 api를 무한으로 불러오는 이슈 해결됨
- usememo 분리
- state들 useeffect 안으로 넣기
- 
- 알 수 없지만 해결 됨.
- 코드 디버깅 직후 해결된 것이 아니라 어디서 해결되었는지 알 수 없음. 아마 네트워크 이슈?
> [Fix] infinite-calling company detail api stopped

- src/components/domain/CompanyTitle.tsx
- src/pages/CompanyDetail.tsx
- 로그인 후에도 저장 버튼이 활성화되지 않았던 문제 해결
- isLoggedIn 에 token 유무 전달
- 
- #42
> [Company] company-save button working well

- src/components/domain/CompanyCard.tsx
- src/components/ui/filter.tsx
- src/index.css
- 기업 간단 카드에서 기업명이 너무 길 시 **...** 처리
- 기존 line-clamp-1 대신 truncate 적용
- 
- #55
> [Map] summarize company name if it's too long

- src/components/layout/header.tsx
- 알림 있을 때 알림 아이콘 디자인 변경
- (흔들림 -> 점 표시)
- hasNewNotification이 true 면 <span>  추가
- 
-
> [Common] if user has new notify, add dots

- src/pages/Main.tsx
- 내 위치 찾기 권한 미허용 시 토스트 메세지가 안 뜨는 에러 해결
- toast 선언 해줌.
- 
- #39
> [Map] fix toast not defined error

- src/components/ui/filter.tsx
- usememo 를 사용하면서 filter가 작업되지 않았던 에러 해결
- 기업 저장 후 저장 됨 필터 눌렀을 때 기업이 뜨지 않고, 재시도 시 뜨는 에러 해결
- usememo 대신 useeffect 사용
- filterTrigger 상태를 넣어서 다시 렌더링해오도록 함
- 
-
> [Map] fix filter not working error

- src/components/domain/CompanyCard.tsx
- src/components/domain/MapOverlay.tsx
- src/components/domain/SearchBar.tsx
- src/components/domain/SuggestionList.tsx
- src/components/ui/button.tsx
- src/components/ui/toggle.tsx
- src/hooks/useFetchSuggestions.ts
- src/pages/Main.tsx
- src/store/search.ts
- 검색창에 검색 결과 눌렀을 때 지도 이동 이벤트 추가
- 검색 결과의 핀이 다른 핀보다 커지도록 효과 추가
- 지도 위의 요소들이 자연스럽게 겹치도록 조절
- 필터, 내 위치 찾기 버튼, 기업 간단 카드, 마커, 검색 결과의 마커 z-index 조절
- 
- #40 
- #21  -> 자연스럽지 않다고 판단하여 폐기
> [Map] searchbar working well

- index.html
- src/App.tsx
- src/hooks/useViewportHeight.ts
- src/layout/MainLayout.tsx
- 갤럭시의 자체 네비게이션 바 때문에 콘텐츠가 가려지는 현상 해결
- 
- 
-
> [Common] resize for android view

- src/pages/Main.tsx
- 클러스터와 마커 겹치는 이슈 해결(기존 3->2개만 판단햇던 것 origin -> origin-1)
- 클러스터 크기 크게
- 
- 
-
> [Map] make every cluster and alone marker seperatable

- src/lib/axios.ts
- src/pages/Main.tsx
- src/pages/Mypage.tsx
> [Fix] reffresh token not fetching error handle

- src/lib/axios.ts
- 로그인 시에도 쿠키를 전달할 수 있게 withCredentials: true를 전역에 해줌
- 
- 
-
> [Common] withCredentials in global instance

- src/lib/axios.ts
- 토큰 재발급 실패 시 재시도 로직 추가
- 그 이상 실패 시 토큰 삭제&로그인 페이지로 강제 이동
- 
- 
-
> [Member] try again if token refresh fail

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
- #97 
- GitHub Actions 스크립트 작성
- GitHub Actions 실행 트리거
-
> 👷 Ci: GitHub Actions 스크립트 작성

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
- #97 
- corepack enable 추가
- 
-
> 👷 Ci: corepack enable 추가

- src/pages/Mypage.tsx
- 빌드 오류 해결을 위해 사용하지 않는 코드 제거
- 
- 
-
> [Member] remove unused code for build

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
- #97 
- dotenv 파일 생성 스텝 추가
- 
-
> 👷 Ci: dotenv 파일 생성 스텝 추가

- .github/workflows/prod_deploy.yml
> 👷 Ci: yml 공백 조절

- src/components/domain/CompanyCard.tsx
- src/components/domain/CompanyTitle.tsx
- src/components/domain/MapOverlay.tsx
- src/hooks/useFetchBookmarkStatus.ts
- src/hooks/useToggleBookmarkMutation.ts
- src/lib/axios.ts
- src/lib/toggleBookmark.ts
- src/pages/CompanyDetail.tsx
- src/pages/Main.tsx
- src/store/company.ts
- 저장 버튼 빨리 클릭 시 저장 무한 증가 발생
- mutation  사용하여 api 호출 및 상태 관리
- 리프레시 토큰 잘 받아 옴
- 토큰 만료가 401이라서 axios 에러에 401도 받도록 처리함. 
- 
- #95
> [Company, Map] use mutation for save state& now gets refresh token perfectly

- src/components/domain/CompanyCard.tsx
- src/pages/Main.tsx
- 기업 간단 카드 어디든 눌러도 기업 상세 페이지로 이동
- 기업 카드를 연 상태로 지도 어디든 눌러도 기업 카드 종료
- 
- 
- #87 
- #94
> [Map] Better company card events

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
- CI/CD 수행 결과를 디스코드 메세지로 전송
- dev_deploy.yml과 prod_deploy.yml에 추가
- GitHub Actions 트리거
-
> Ci/#113 - CI/CD 수행 결과를 디스코드 메세지로 전송

- src/components/domain/CompanyCard.tsx
- src/components/domain/CompanyTitle.tsx
- src/layout/MainLayout.tsx
- src/lib/axios.ts
- src/lib/logout.ts
- src/pages/Main.tsx
- src/pages/Mypage.tsx
- 중복 POST 날리기 금지
- 토스트 메세지를 띄울 때 더 쉽게 코드 구성 가능
- axios 에러 에서도 에러 토스트 사용
- 중복 POST 날리면 하나 cancel 함.
- useToast 직접 호출 대신 toast 사용
- MainLayout.tsx에 Toaster 붙임
- 
- #112
> [Member] ignore double POST&easier toast

- .github/workflows/prod_deploy.yml
- AWS Migration에 따른 CI/CD (PROD) 수정
- #125 
- github actions 트리거
-
> 👷 Ci: AWS Migration

- src/lib/axios.ts
- 존재하지 않는 사용자일 시 강제 로그아웃
- 
- 
- 디비를 날려서 생긴 이슈.
> (Feat) force logout on nonexsiting member

- .github/workflows/prod_deploy.yml
- 👷 Ci: DEV-PROD CI/CD 변수처리
- 
- 
-
> 👷 Ci: DEV-PROD CI/CD 변수처리

- .github/workflows/prod_deploy.yml
- src/lib/axios.ts
> DEV-PROD CI/CD 변수처리

- .github/workflows/lint.yml
- `git diff`를 활용하여 변경사항이 있는 코드만 검사
- `git diff`를 활용하여 변경사항이 있는 코드만 검사
- 
-
> 👷 Ci: git diff를 활용하여 변경사항이 있는 코드만 검사

- src/features/Map/Main.tsx
- src/features/Map/components/filter.tsx
- src/features/Map/store/marker.ts
- src/features/Map/util/fetchBookmarkedIds.ts
- 채용 상태의 값 오타 수정
- useEffect의 불필요한 의존성 제거
- fetchBookmarkedIds 파일로 분리
- 
- 
-
> (Fix) filter recruitement works well

- src/components/ui/dropdown.tsx
- src/components/ui/select.tsx
- src/features/Member/profile/Quit.tsx
- src/router/index.tsx
- 회원 탈퇴 페이지 제작
- 드롭 다운 공통 컴포넌트 제작
- 
- 
-
> [Member] make quit page

- src/features/Member/profile/components/footer.tsx
- src/features/Member/service/developers.tsx
- src/layout/MainLayout.tsx
- src/router/index.tsx
- 개발자들 페이지 퍼블리싱
- buy me a coffee 계정 생성
- 
- 
-
> [Member] publish developers page

- src/features/Member/resume/components/longtextForm.tsx
- src/features/Member/resume/components/numberForm.tsx
- src/features/Member/resume/components/textForm.tsx
- src/features/Member/resume/resumeForm.tsx
- 선호 직무, 백준 티어, 자격증 개수, 프로젝트 개수, 전공 여부만 입력해도 폼 제출 가능하게 함.
- 폼 제출 후의 url을 /resume/download로 변경
- 
- 
-
> [Resume] new setting for form submit condition

- src/features/Map/Main.tsx
- src/features/Map/components/SearchBar.tsx
- 지도 페이지에서 스크롤바 생기던 문제 해결
- 최소 축소 범위 성남시로 제한
- Main.tsx와 SearchBar.tsx에 혼재해 있던 자동 추천관련 코드 모두 SearchBar.tsx로 이동
- 
- 
-
> [Fix] remove unused scrollbar on map page&limit min zoom level

- src/hooks/useToast.ts
- 빌드 오류 타입 단언으로 해결
- open: boolean
- 
-
> (Fix) add type assertion for 'open'

- src/features/Company/CompanyDetail.tsx
- 기획 변경으로 인한 작년 채용 현황 공지 기능 제거
- import 순서 재배열
- 남겨놨던 주석 제거
- 
- #53
> (Chore) remove all last year recruitment status codes

- src/features/Member/auth/OAuthCallback.tsx
- src/features/Member/auth/store/auth.ts
- src/features/Member/auth/utils/axios.ts
- src/features/Member/auth/utils/kakaoLogin.ts
- src/lib/request.ts
- isTokenExpired, shouldForceLogout 에서 타입 오류 해결
- 로그아웃 시 토큰 완전 삭제
- 헤더에 토큰 null을 담고 요청 시 강제 로그아웃 
- 
- 
- 
-
> (Fix) public request type mismatch

- package.json
- pnpm-lock.yaml
- src/features/Member/auth/OAuthCallback.tsx
- src/features/Member/auth/utils/logout.ts
- src/features/Member/profile/Mypage.tsx
- src/hooks/useUserInfo.ts
- src/lib/getUserInfo.ts
- src/main.tsx
- 유저 정보를 저장하기 위해 탠스택 쿼리 사용
- 로그인 성공 시 메인 페이지로 리다이렉트
- 
- 
-
> (Refact) use query cache for user info data

- src/features/Competition/Ranking.tsx
- 대회 입장과 관련된 API 연동
- 대회 id 조회
- 대회 참가 여부 조회
- 
- 
- #131
> [Competition] connect competition entrance API

- src/features/Competition/Competition.tsx
- src/features/Competition/components/question.tsx
- 문제 풀이 영역 높이, 너비 고정
- 화살표 클릭 시 다음, 이전 문제로 이동
- 
- 
-
> [Competition] design changes to problem solving areat

- .gitignore
- src/features/Competition/Competition.tsx
- src/features/Competition/Ranking.tsx
- src/features/Competition/components/question.tsx
- src/features/Competition/store/competitionStore.ts
- 문제 풀이와 관련된 API 연결
- 대회 문제 GET
- 대회 참가 POST
- 대회 제출 POST
- 
- 
- #131
> [Competition] connect problem solving API

- src/features/Competition/Competition.tsx
- src/features/Competition/Ranking.tsx
- src/features/Competition/components/timer.tsx
- 타이머 함수 분리
- 대회 진입 시 남은 시간 표시
- 
- 
-
> [Competition] perfect timer for competition

- src/components/layout/header.tsx
- src/components/ui/modal.tsx
- src/features/Competition/Competition.tsx
- src/features/Competition/hooks/useCompetitionData.ts
- src/features/Competition/hooks/useCompetitionSubmit.ts
- src/features/Competition/hooks/useCompetitionTimer.ts
- 대회 시간 초과 시 대회 종료 모달 생성
- 대회 중, 뒤로가기 클릭 시 경고 모달 생성
- 상태기반 트리거되는 모달 컴포넌트 작성
- Competition.tsx 역할 분리 리팩토링
- 
-
> [Competition] add warning modals for competition/entry page

- src/features/Competition/utils/chartUtils.ts
- src/features/Competition/utils/dailyChart.tsx
- src/features/Competition/utils/monthlyChart.tsx
- dailyChart.tsx와 monthlyChart.tsx에 중복되어있던 코드 util로 분리
- 
- 
-
> [Competition] Separate reusable D3 chart utils and inject x/y scale from parent components

- src/features/Map/components/CompanyCard.tsx
- src/features/Member/profile/Mypage.tsx
- src/features/Member/profile/components/wishCompanyList.tsx
- 마이페이지에 관심 기업 목록 컴포넌트 api 연동
- 
- 
-
> [Member] fetch API for wish company list at mypage

- src/features/Competition/Ranking.tsx
- src/features/Competition/components/myRankCard.tsx
- src/features/Competition/hooks/useMyRanking.ts
- src/features/Competition/hooks/useTopRanking.ts
- src/features/Competition/utils/chartUtils.ts
- src/features/Competition/utils/dailyChart.tsx
- src/features/Competition/utils/monthlyChart.tsx
- 내 랭킹 조회 api 연동
- top10 랭킹 조회 api 연동
- Ranking.tsx에서 내 랭킹 컴포넌트 분리
- 
- 
-
> [Competition] API for fetching ranking data

- src/features/Competition/Ranking.tsx
- 랭킹 데이터가 존재할 때만 랭킹 보여줌
- 없을 시 fallback
- 
- 
-
> (HOTFIX) show ranking only when data is truthy

- .github/workflows/prod_deploy.yml
- Dockerfile
> 👷 Docker 기반 컨테이너 환경으로의 전환

- .github/workflows/prod_deploy.yml
> 👷 Ci: ECR Login

- src/components/layout/header.tsx
- src/features/Competition/Competition.tsx
- src/features/Competition/Ranking.tsx
- src/features/Competition/components/timer.tsx
- src/features/Competition/config/competitionTime.ts
- src/features/Competition/hooks/useCompetitionData.ts
- src/features/Competition/hooks/useCompetitionSubmit.ts
- src/features/Competition/hooks/useCompetitionTimer.ts
- src/features/Competition/store/competitionStore.ts
- api 요청 에러 해결
- 타이머 로직에 공통적으로 UTC 시간 사용
- 대회 시작, 끝 시간을 상수로 설정
- 대회 중 뒤로 가기, 로고 클릭 시 확인 모달 팝업 여부 분기
- 
- 
-
> [Competition] fix api errors & use UTC time for timer & conditional modal

- src/features/Member/profile/components/wishCompanyList.tsx
- 관심 기업이 없을 떄 관심 기업 마지막을 나타내는 컴포넌트를 숨김
- 
- 
-
> [Member] do not show EOL component if there's nothing on wish companies

- src/features/Member/profile/Mypage.tsx
- src/router/index.tsx
- 배포 서버에 미구현 기능이 올라가 있는 오류 해결
- 미구현 기능이 있는 페이지는 강제로 리다이렉션 추가
- 관심 기업 리스트 주석 처리
- 
-
> (Fix) change router domain for unfinished pages

- .github/workflows/prod_deploy.yml
- ♻️ Refactor: Docker build 옵션 수정
- 
- 
-
> ♻️ Refactor: Docker build 옵션 수정

- .github/workflows/prod_deploy.yml
> ♻️ Refactor: sed 수정

- .github/workflows/prod_deploy.yml
> 👷 Ci: sed 수정

- .github/workflows/prod_deploy.yml
- src/features/Member/profile/Mypage.tsx
- src/router/index.tsx
> 👷 Ci: sed 다시 수정

- src/features/Competition/Competition.tsx
- src/features/Competition/Ranking.tsx
- src/features/Competition/components/timer.tsx
- src/features/Competition/config/competitionTime.ts
- src/features/Competition/hooks/useCompetitionData.ts
- src/features/Competition/hooks/useCompetitionSubmit.ts
- src/features/Competition/hooks/useCompetitionTimer.ts
- src/features/Competition/store/competitionStore.ts
- src/features/Member/auth/utils/authManager.ts
- src/features/Member/auth/utils/logout.ts
- 대회 문제 풀이 시나리오 성공
- 대회 참가 제출에 authorization 누락되었던 에러 해결
- 타이머가 00:00:00으로 고정되어 있던 에러 해결
- 대회 결과 제출 시 경과 시간을 대회에 참가해있던 시간만 계산하여 전달
- 
-
> [Competition] competition problem solving working just fine

- .github/workflows/prod_deploy.yml
- src/features/Competition/Competition.tsx
- src/features/Competition/Ranking.tsx
- src/features/Competition/components/timer.tsx
- src/features/Competition/config/competitionTime.ts
- src/features/Competition/hooks/useCompetitionData.ts
- src/features/Competition/hooks/useCompetitionSubmit.ts
- src/features/Competition/hooks/useCompetitionTimer.ts
- src/features/Competition/store/competitionStore.ts
- src/features/Member/auth/utils/authManager.ts
- src/features/Member/auth/utils/logout.ts
- src/features/Member/profile/Mypage.tsx
- src/router/index.tsx
> 미기능 개발 미노출

- src/features/Member/auth/utils/authManager.ts
- src/router/index.tsx
> (Fix) change reissue url to dev-api

- src/features/Member/auth/utils/authManager.ts
- src/router/index.tsx
> (Fix) do not retry on reissue fail

- src/features/Member/auth/utils/authManager.ts
- src/router/index.tsx
> (Feat) do not send reissue again

- src/features/Member/auth/utils/authManager.ts
- 토큰 재발급 필요시 이전 요청을 큐에 저장함.
- 재발급은 큐에 넣지 않음
- 
- 
-
> (Fix) add queue before reissue

- src/features/Competition/Ranking.tsx
- src/features/Competition/components/timer.tsx
- src/features/Competition/hooks/useTopRanking.ts
- 대회 진행 시각일 시에 polling으로 실시간 데이터 가져옴. 5초
- 
- 
-
> [Competition] use polling for daily ranking on time

- src/App.tsx
- src/features/Competition/Competition.tsx
- src/features/Competition/hooks/useCompetitionSubmit.ts
- src/features/Member/auth/store/auth.ts
- src/features/Member/notification/hooks/useNotificationSSE.ts
> [Common] move token to session storage

- src/features/Member/notification/Notification.tsx
- src/features/Member/notification/hooks/useNotification.ts
> [Notification] infinite scroll for notifications

- src/App.tsx
- src/features/Member/notification/hooks/useNotificationSSE.ts
- SSE 연결 요청 시, 무조건 이전 요청을 중지하고 새로 요청 받아옴.
- 
- 
-
> [Fix] reconnect SSE on every disconnection.

- src/features/Member/notification/Notification.tsx
- 알림이 없을 때 해당 카테고리 하위 아무것도 보여주지 않음
- 
- 
-
> [Notification] hide notif texts on no new notifications

- src/features/Competition/Ranking.tsx
- src/features/Competition/components/myRankCard.tsx
- src/features/Competition/components/rankCardList.tsx
- src/features/Competition/hooks/useMyRanking.ts
- src/features/Competition/hooks/useTopRanking.ts
- 내 랭킹 보여주기
- 내 실시간 랭킹 보여주기
- 
- 
-
> [Competition] show my rank

- src/App.tsx
- src/features/Member/notification/components/notify.tsx
- 알림 템플릿을 프론트에서 정적으로 소유
- 
- 
-
> [Notification] fix format for each notifications

- src/features/Competition/hooks/useMyRanking.ts
- 실시간 랭킹 api 요청에서 누락된 헤더 추가
- 
- 
-
> [Competition]  add authorization to request header

- src/features/Map/components/CompanyCard.tsx
- src/features/Member/profile/components/wishCompanyList.tsx
- 관심 기업 리스트에서 저장 해제 가능
- 
- 
-
> [Member] sucessful wish company save toggle

- src/features/Member/profile/Account.tsx
- src/features/Member/profile/Mypage.tsx
- src/features/Member/profile/util/submitProfileUpdate.ts
- 닉네임은 항상 보내주고, 프로필 이미지는 변경이 있을 때만 보내주기
- 마이페이지 프로필 이미지 디자인 수정
- 
- 
-
> [Member] successful profile update on every circumstances

- public/assets/blue-rank.svg
- public/assets/green-rank.svg
- public/assets/red-rank.svg
- public/assets/yellow-rank.svg
- src/features/Competition/components/myRankCard.tsx
- src/features/Competition/hooks/useCompetitionSubmit.ts
- src/features/Competition/hooks/useCompetitionTimer.ts
- src/features/Competition/hooks/useMyRanking.ts
- src/features/Competition/utils/chartUtils.ts
- src/features/Competition/utils/dailyChart.tsx
- src/features/Competition/utils/periodicChart.tsx
- src/features/Member/notification/components/notify.tsx
- 소요 시간이 음수로 표현되던 거 해결
- 포맷 수정
- 
-
> [Competition] fix rank bar formats

- .github/workflows/prod_deploy.yml
- #259 
- 👷 Ci: ssm 명령 수정
- 
-
> 👷 Ci: ssm 명령 수정

- src/features/Member/profile/Quit.tsx
- src/lib/request.ts
> [Member] develop member quit function (#262)

- src/features/Competition/components/aggregationNotice.tsx
- src/features/Competition/hooks/useMyRanking.ts
- src/features/Competition/hooks/useTopRanking.ts
- 실시간 랭킹 polling 전에 한 번 그리고 polling 실행
- 
- 
-
> [Competition] live rank shown properly

- src/features/Competition/Ranking.tsx
- 시간에 맞춰서 새로고침 하지 않아도 대회 타이머, 대회 참가 버튼이 변하도록 수정
- competitionTIme 여부를 interval을 붙여서 초마다 판단
- 
-
> [Competition] refresh competition timer button just on time

- src/features/Member/auth/OAuthCallback.tsx
- 회원 탈퇴 후 재로그인 시 토스트로 탈퇴한 회원임을 명시
- 
- 
-
> [Member] alert blocking relogin after quit

- src/features/Competition/components/myRankCard.tsx
- src/features/Competition/hooks/useCompetitionSubmit.ts
- src/features/Competition/hooks/useCompetitionTimer.ts
- src/features/Member/notification/hooks/useNotificationSSE.ts
- src/features/Member/profile/Mypage.tsx
- src/lib/getUserInfo.ts
> (Fix) update calculating competition elapsed time logic

- src/features/Member/notification/Notification.tsx
> (Fix) add auto scroll to notification page

- src/features/Member/profile/Account.tsx
- src/features/Member/profile/util/handlePresignedUrl.ts
- src/features/Member/profile/util/submitProfileUpdate.ts
- src/features/Member/resume/store/resumeStore.ts
- src/features/Member/resume/upload.tsx
- src/features/Member/resume/util/uploadPdf.ts
> [Resume] upload resume and fetch response

- src/lib/request.ts
> (Fix) fix type error

- src/layout/MainLayout.tsx
> (Fix) give scroll to main component

- src/components/layout/navbar.tsx
- 상점 도메인 이름 변경 건에 따른 404 페이지 보여짐 이슈 해결
- 
- 
-
> (Fix) upate store to shop

- src/pages/ToBeContinued.tsx
- 개발 예정 페이지의 높이를 재조정해서 페이지 이동시 네비게이션 바의 높이가 바뀌던 이슈 해결
- 
- 
-
> [Common] update height for toBeContinued page

- src/features/Competition/components/myRankCard.tsx
> (Fix) show my ranking

- src/features/Competition/components/myRankCard.tsx
- 대회 시간이 아닐 때도 일일 내 랭킹을 볼 수 있게 변경
- 
- 
-
> (Hotfix) show my ranking after competition time

- .github/workflows/prod_deploy.yml
> 👷 Ci: Update CI process

- app/api/revalidate-issue/route.ts
- next.config.ts
- src/entities/company/api/fetchRecruitments.ts
- src/features/shop/api/useHandleBuyTicket.ts
- src/features/shop/ui/Product.tsx
- src/features/shop/ui/ProductList.tsx
> [Company] POST recent issue with changed company ids

- app/company/[id]/page.tsx
- src/entities/company/api/fetchIssue.ts
- src/entities/company/api/fetchRecruitments.ts
- src/entities/company/api/fetchWishCount.ts
- src/entities/company/model/companyType.ts
- src/entities/company/ui/CompanyDetail.tsx
- src/entities/company/ui/CompanyGallery.tsx
- src/entities/company/ui/CompanyTab.tsx
- src/entities/company/ui/RecruitmentBanner.tsx
- src/entities/company/ui/issue.tsx
- src/entities/company/ui/recruit.tsx
- src/features/company/ui/BookmarkButton.tsx
- src/features/shop/ui/Product.tsx
- src/shared/api/useToggleBookmarkMutation.ts
- company detail 바뀐 API 명세에 따른 데이터 fetch 로직 수정
- wishCount, recente-issue, recruitments 따로 fetch
- 상품 품절 시 구매하기 버튼 비활성화
- 
- 
-
> [Company] ISR for company recent-issue tab

- .github/workflows/prod_deploy.yml
- Dockerfile
- #328 
- 👷 Ci: Update Dockerfile
- 
-
> 👷 Ci: Update Dockerfile

- .github/workflows/prod_deploy.yml
- #328 
- Ci: env -> next로 폴더이름
- 
-
> 👷 Ci: env -> next로 폴더이름

- .github/workflows/prod_deploy.yml
- Dockerfile
- #328 
- Dockerfile - PORT 5173
- 
-
> Dockerfile - PORT 5173

- .github/workflows/prod_deploy.yml
- Dockerfile
> 👷 Ci: 다시 빠꾸

- Dockerfile
- ✏️ Fix: 오타 수정
- ✏️ Fix: 오타 수정
- 
-
> ✏️ Fix: 오타 수정

- app/competition/entry/page.tsx
- src/features/competition/model/useCompetitionSubmit.ts
- 대회 소요 시간을 계산하기 위해서 상태 대신 Date.now() 사용.
- 
- 
-
> [Competition] use local date time to calculate elapsed time

- src/entities/company/ui/CompanyGallery.tsx
- src/entities/map/ui/CompanyCard.tsx
- src/features/company/ui/BookmarkButton.tsx
- 맵 위의 기업 카드에서 로고에 img태그 사용. 
- 
- 
- 추후 최적화 예정
> [Map] use <img> for company logo at company card

- src/entities/map/ui/CompanyCard.tsx
> (Fix) fix build error

- .gitignore
- middleware.ts
- package.json
- tsconfig.json
- 강제 라우팅을 막기 위한 미들웨어 추가
- https:// 로 열리;는  dev 명령어 추가
- 
- 
-
> [Common] middleware for unexpected routing

- middleware.ts
> (Fix) pass middleware on development mode

- src/entities/competition/lib/convertToChartProps.ts
- src/features/competition/model/useCompetitionSubmit.ts
- src/features/competition/ui/myRankCard.tsx
- src/features/member/ui/Profile.tsx
- src/features/member/ui/profileImageInput.tsx
> (Fix) proper fallback img for profile image

- app/competition/entry/page.tsx
- src/features/competition/ui/question.tsx
- 문제 수 상관없이 대회 제출 가능토록
- 
- 
-
> [Competition] flexible questions numbers

- app/competition/entry/page.tsx
- src/entities/map/api/useCompanyList.ts
- src/features/competition/ui/question.tsx
- src/features/map/model/map.ts
- 문제 수 상관없이 대회 문제 풀 수 있도록
- 지도 첫 진입 시 마커가 보이지 않는 문제 해결
- 
- 
-
> V3 버그 수정 2차

- package.json
- pnpm-lock.yaml
- src/features/resume/download/ui/AnswerForm.tsx
- src/features/resume/download/ui/Question.tsx
- src/features/resume/form/ui/longtextForm.tsx
- 질문에 마크다운 문법 적용
- 고급 이력서 다운로드 준비 완료시 모달 띄우기
- 
- 
-
> [Resume] adapt markdown for question

- src/features/resume/download/model/answerStore.ts
- src/features/resume/download/ui/AdvancedDownloadModal.tsx
- src/features/resume/download/ui/Question.tsx
- src/features/resume/form/ui/FormTitle.tsx
- 설명 문구 바꿈
- 이력서 생성 시 설명 문구 추가
- 고급 이력서 다운로드 모달에서 홈으로 버튼 제거
- 
- 
-
> [Resume] some description changes

- src/shared/lib/Seo.tsx
> (Feat) update description tag
